# Generated by Django 4.2.5 on 2023-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hydro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('viscosity', models.FloatField()),
                ('t_initial', models.FloatField()),
                ('t_final', models.FloatField()),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('viscosity', models.FloatField()),
                ('magnetic_diffusivity', models.FloatField()),
                ('t_initial', models.FloatField()),
                ('t_final', models.FloatField()),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('viscosity', models.FloatField()),
                ('critical_rayleigh_number', models.FloatField()),
                ('rayleigh_number', models.FloatField()),
                ('prandtl_number', models.FloatField()),
                ('thermal_diffusivity', models.FloatField()),
                ('t_initial', models.FloatField()),
                ('t_final', models.FloatField()),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField()),
                ('resolution', models.CharField(max_length=20)),
                ('viscosity', models.FloatField()),
                ('critical_rayleigh_number', models.FloatField()),
                ('rayleigh_number', models.FloatField()),
                ('prandtl_number', models.FloatField()),
                ('thermal_diffusivity', models.FloatField()),
                ('t_initial', models.FloatField()),
                ('t_final', models.FloatField()),
                ('path', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
