# Generated by Django 4.2.5 on 2023-09-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbulenceWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydro',
            name='initial_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mhd',
            name='initial_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rbc',
            name='initial_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scalar',
            name='initial_condition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
