# Generated by Django 5.0.1 on 2024-01-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "turbulenceWeb",
            "0002_hydro_initial_condition_mhd_initial_condition_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompressibleConvection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension", models.IntegerField()),
                ("resolution", models.CharField(max_length=20)),
                ("initial_condition", models.CharField(max_length=255, null=True)),
                ("aspect_ratio", models.FloatField()),
                ("epsilon", models.FloatField()),
                ("dissipation_number", models.FloatField()),
                ("gamma", models.FloatField()),
                ("prandtl_number", models.FloatField()),
                ("reyleigh_number", models.FloatField()),
                ("t_initial", models.FloatField()),
                ("t_final", models.FloatField()),
                ("path", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
